apiVersion: v1
kind: Service
metadata:
  name: code-reviewer-service
spec:
  type: NodePort
  selector:
    app: code-reviewer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080 