"""Add metrics and issues columns

Revision ID: 0b44e72a561b
Revises: 
Create Date: 2025-05-21 01:24:18.369332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b44e72a561b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_analyses', sa.Column('metrics', sa.JSON(), nullable=True))
    op.alter_column('code_analyses', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('code_analyses', 'pylint_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'complexity_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'maintainability_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'security_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'overall_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('code_analyses', 'code_size')
    op.drop_column('code_analyses', 'function_count')
    op.drop_column('code_analyses', 'comment_ratio')
    op.drop_column('code_analyses', 'pylint_issues')
    op.drop_column('code_analyses', 'test_coverage')
    op.drop_column('code_analyses', 'class_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_analyses', sa.Column('class_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('code_analyses', sa.Column('test_coverage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('code_analyses', sa.Column('pylint_issues', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('code_analyses', sa.Column('comment_ratio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('code_analyses', sa.Column('function_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('code_analyses', sa.Column('code_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('code_analyses', 'overall_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'security_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'maintainability_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'complexity_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'pylint_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('code_analyses', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('code_analyses', 'metrics')
    # ### end Alembic commands ###
