"""Add repository information to code analyses

Revision ID: 84bc3b14104a
Revises: 0b44e72a561b
Create Date: 2025-05-21 01:58:55.102991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bc3b14104a'
down_revision: Union[str, None] = '0b44e72a561b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_analyses', sa.Column('repository', sa.String(), nullable=True))
    op.add_column('code_analyses', sa.Column('commit_sha', sa.String(), nullable=True))
    op.add_column('code_analyses', sa.Column('commit_message', sa.String(), nullable=True))
    op.add_column('code_analyses', sa.Column('commit_author', sa.String(), nullable=True))
    op.add_column('code_analyses', sa.Column('file_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_code_analyses_commit_sha'), 'code_analyses', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_code_analyses_repository'), 'code_analyses', ['repository'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_analyses_repository'), table_name='code_analyses')
    op.drop_index(op.f('ix_code_analyses_commit_sha'), table_name='code_analyses')
    op.drop_column('code_analyses', 'file_path')
    op.drop_column('code_analyses', 'commit_author')
    op.drop_column('code_analyses', 'commit_message')
    op.drop_column('code_analyses', 'commit_sha')
    op.drop_column('code_analyses', 'repository')
    # ### end Alembic commands ###
